language: php

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  # Branch: 37_STABLE can support PHP 7.1, 7.2, 7.3
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - MOODLE_BRANCH=MOODLE_37_STABLE
  matrix:
    - DB=pgsql
    - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0.0
  - nvm use 14.0.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache